<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <!--<TestingPlatformDisableCustomTestTarget>true</TestingPlatformDisableCustomTestTarget>-->
    <!--<IsTestingPlatformApplication>false</IsTestingPlatformApplication>-->
    <!--<TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>-->
  </PropertyGroup>
</Project>
